### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by eakteam** [rly0nheart/thedevilseye#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/thedevilseye", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/thedevilseye/main.py", line 15, in main
    devils_eye = TheDevilsEye()
  File "/usr/local/lib/python3.8/dist-packages/thedevilseye/thedevilseye.py", line 15, in __init__
    self.driver = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/firefox/webdriver.py", line 196, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```

**Comment by rly0nheart** [comment]
Hello @eakteam, do you have Firefox installed on your system?

**Comment by eakteam** [comment]
> Hello @eakteam, do you have Firefox installed on your system?

I am testing it from Windows Subsystem for Linux, it's just terminal.

**Comment by rly0nheart** [comment]
> > Hello @eakteam, do you have Firefox installed on your system?
> 
> I am testing it from Windows Subsystem for Linux, it's just terminal.

What Linux distro do you have installed in your Windows Subsystem for Linux?

**Comment by eakteam** [comment]
Ubuntu

**Comment by rly0nheart** [comment]
> Ubuntu

Alright, first here are a few steps you can follow to first install firefox in your WSL distro:

**1. Install software-properties-common**
```
sudo apt install software-properties-common -y
```

**2. Add Mozilla apt repository**
```
sudo add-apt-repository ppa:mozillateam/ppa
```

**3. Create the mozillateamppa file**
```
sudo vi /etc/apt/preferences.d/mozillateamppa
```
> You can use any text editor of your choice

**4. Add the following lines to the file and save it**
```
Package: firefox*
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 501
```
**5. Once done, run the following to install Firefox**
```
sudo apt update && sudo apt install firefox -y
```


Secondly (and lastly), setup geckodriver

**1. Install curl**
```
sudo apt install curl -y
```

**2. Download Geckodriver and extract it**
```
curl -L https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.32.2-linux64.tar.gz | sudo tar xz -C /usr/local/bin
```

Once this is done, you should be able to run ``thedevilseye``,  good luck and let me know how it goes!✌️😊

**Comment by Sudococommunity** [comment]
I am having traceback error 
![Uploading 16843470743373727434025819923767.jpg…]()

**Comment by rly0nheart** [comment]
Have you properly setup selenium?

**Comment by Sudococommunity** [comment]
I actually don't know i did that or not  i just run the given command

**Comment by rly0nheart** [comment]
You probably haven't setup selenium. follow the setup instructions for selenium in the README or here https://github.com/rly0nheart/thedevilseye/issues/1#issuecomment-1481785855

Edit:
I'm currently working on a better tool that will not require selenium

**Comment by Sudococommunity** [comment]
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 103, in __init__
    self.sourceslist = SourcesList()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 276, in __init__
    self.refresh()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 292, in refresh
    self.matcher.match(source)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 484, in match
    if (re.search(template.match_uri, source.uri) and
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 2
This error pops when i run command 
"$sudo add-apt-repository ppa:mozillateam/ppa"

**Comment by rly0nheart** [comment]
> Traceback (most recent call last):
>   File "/usr/bin/add-apt-repository", line 95, in <module>
>     sp = SoftwareProperties(options=options)
>   File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 103, in __init__
>     self.sourceslist = SourcesList()
>   File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 276, in __init__
>     self.refresh()
>   File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 292, in refresh
>     self.matcher.match(source)
>   File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 484, in match
>     if (re.search(template.match_uri, source.uri) and
>   File "/usr/lib/python3.9/re.py", line 201, in search
>     return _compile(pattern, flags).search(string)
>   File "/usr/lib/python3.9/re.py", line 304, in _compile
>     p = sre_compile.compile(pattern, flags)
>   File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
>     p = sre_parse.parse(p, flags)
>   File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
>     p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
>   File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
>     itemsappend(_parse(source, state, verbose, nested + 1,
>   File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
>     p = _parse_sub(source, state, sub_verbose, nested + 1)
>   File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
>     itemsappend(_parse(source, state, verbose, nested + 1,
>   File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
>     p = _parse_sub(source, state, sub_verbose, nested + 1)
>   File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
>     itemsappend(_parse(source, state, verbose, nested + 1,
>   File "/usr/lib/python3.9/sre_parse.py", line 668, in _parse
>     raise source.error("nothing to repeat",
> re.error: nothing to repeat at position 2
> This error pops when i run command 
> "$sudo add-apt-repository ppa:mozillateam/ppa"

Can you provide more information on these errors?

Can you send a screenshot of each command you'll be running?

**Comment by Sudococommunity** [comment]
actually i have problem with add-apt-repository pyhton program this error i think thats why this occur as i tried using another command in order to install lutris still get same error 
![Uploading 16844436534675271397230734232235.jpg…]()

**Comment by Sudococommunity** [comment]
my add-apt-repository command unable to add any repository in it

**Comment by Sudococommunity** [comment]
[apt-add-repository.txt](https://github.com/rly0nheart/thedevilseye/files/11511715/apt-add-repository.txt)
it is add-apt-repository file that causing problem

**Comment by rly0nheart** [comment]
> actually i have problem with add-apt-repository pyhton program this error i think thats why this occur as i tried using another command in order to install lutris still get same error 
> ![Uploading 16844436534675271397230734232235.jpg…]()
> 

1. What system are you using?
2. How did you install the add-apt-repository command?
3. In order for me to properly help, you might need to to add screenshot of the commands you're running

**Comment by Sudococommunity** [comment]
![add-apt-repository](https://github.com/rly0nheart/thedevilseye/assets/98217143/0cd112ad-5fc9-4c38-80b8-c3f334314d48)
here it is my screen shot

**Comment by Sudococommunity** [comment]
![Screenshot at 2023-05-19 03-03-38](https://github.com/rly0nheart/thedevilseye/assets/98217143/67a204f1-eea4-4967-b233-af4e0c8f654d)

**Comment by Sudococommunity** [comment]
![error](https://github.com/rly0nheart/thedevilseye/assets/98217143/2f6c107e-5c41-4d13-8c00-9f7fb553589e)

**Comment by Sudococommunity** [comment]
help me bro i think i break the system

**Comment by Sudococommunity** [comment]
i have installed the firefox by default

**Comment by Sudococommunity** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/thedevilseye", line 5, in <module>
    from thedevilseye.main import main
  File "/usr/local/lib/python3.9/dist-packages/thedevilseye/main.py", line 4, in <module>
    from thedevilseye.thedevilseye import *
  File "/usr/local/lib/python3.9/dist-packages/thedevilseye/thedevilseye.py", line 8
    from thedevilseye.config import RED. GREEN. RESET
                                       ^
SyntaxError: invalid syntax

**Comment by Sudococommunity** [comment]
this is the error i am facing when i run the command

**Comment by Sudococommunity** [comment]
![Screenshot at 2023-05-19 03-40-02](https://github.com/rly0nheart/thedevilseye/assets/98217143/f0300a3b-a47f-4969-b960-a4e26f27c841)

**Comment by Sudococommunity** [comment]
Bro why you stop responding me

**Comment by rly0nheart** [comment]
> Bro why you stop responding me

Hey @Sudococommunity Uninstall the one you have and install the latest release v1.6.0 that I just published. You wont need to setup selenium for this release, just install and run it. Use `thedevilseye --help` to see the usage (this release has got some new features)
Enjoy! :)
